### ISSUE TITLE
AutoStart

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS_Projection#2]
Would be great to have a way to autostart a projection using this tools

It might not be something to implement directly in the JS (or maybe I don't know) but more to document in the wiki the process (it will be different depending also on the OS).

For Mac it should be something like this

- On the mac itself http://osxdaily.com/2006/11/29/how-to-launch-application-on-system-start-in-mac-os-x/

- And then I don't know how to ask Chrome to run  2 different displays (with different content ),

 Could be it be a parameters in index.html (like the path for display 1, the path for display 2 and then the instruction to open 2 window? or in the chrome settings?

`````
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome __PATH__/index.html --kiosk
`````

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_cityscopeJS_Projection#kiosk-mode-and-auto-start

**Comment by agrignard** [comment]
It says not in full screen in the doc is there a way to set in in full screen automatically ?

**Comment by RELNO** [comment]
looks like this `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome google.com  --kiosk` goes into full screen *if* chrome is closed beforehand

**Comment by agrignard** [comment]
I don't get the end of this issue, is it close because it works or because it's impossible? Does anyone has the opportunity to test it with 2 displays?

**Comment by RELNO** [comment]
@agrignard as https://github.com/CityScope/CS_cityscopeJS_Projection/issues/2#issuecomment-578766086 mentions, if you set up the tool in kiosk mode AND have a new chrome instance (i.e no chrome is running in the background) than starting from the bash command /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome google.com --kiosk will take you to full screen. 

However, I would not trust this to be your go to solution for the exhibition -- a simple write up of how to start chrome and get it to full screen would be 'curator-proof'.

**Comment by nayoub** [comment]
Automation process: 
Travel to root of CS_cityscopeJS_Projection folder and launch
`python3 -m http.server --cgi 8080`
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome http://0.0.0.0:8080/
`

(Python 3 needs to be installed on the Mac Mini as well)

**Comment by agrignard** [comment]
After running this in CS_cityscopeJS_Projection
`````
Arno:CS_cityscopeJS_Projection Arno$ python3 -m http.server --cgi 8080 /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome http://0.0.0.0:8080/
`````
I get this error
`````
usage: server.py [-h] [--cgi] [--bind ADDRESS] [port]
server.py: error: unrecognized arguments: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome http://0.0.0.0:8080/
`````

**Comment by RELNO** [comment]
> I get this error

These are two shell commands that should be run one after the other, not at once. 
Try `python3 -m http.server --cgi 8080`
open new terminal: 
`/Applications/GoogleChrome.app/Contents/MacOS/Google Chrome http://0.0.0.0:8080/`

**Comment by RELNO** [comment]
https://github.com/CityScope/CS_cityscopeJS_Projection/commit/e3cf210a125ec9737ae5b01030c6f3e20598757f simplfies the tool, but for now removes some of these more complex (and mostly local) features. I'll look into adding them later if needed.
