### ISSUE TITLE
Projection broken?

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS_Projection#6]
I do not manage to display anything since a recent pull, am I missing something? 

My video are in a media folder and I use the browse files interface.

Any help is welcome

**Comment by RELNO** [comment]
Can't replicate.. can you share the console log?

**Comment by agrignard** [comment]
Should I use localhost?

**Comment by RELNO** [comment]
yes https://github.com/CityScope/CS_cityscopeJS_Projection#usage

**Comment by RELNO** [comment]
even if it looked like it was running before, it wasn't, you only saw the basic html loading without functionality. There is virtually no js running without localHost.

**Comment by agrignard** [comment]
Ok it works with (http://0.0.0.0:8000/index.html) it used to wotk without localhost (maybe we need to had in the doc that a local server should be strated e.g python -m http.server)

**Comment by RELNO** [comment]
> python -m http.server

this is one way to start LH, but not a great one since it lock a PID even after the terminal is closed. So for example if the app crashes, the local server is locked and user see `Cannot Access Local Server (http://localhost:8080)`

**Comment by agrignard** [comment]
What would be a better way to start a LH?

**Comment by RELNO** [comment]
The python method is valid, only it's important to document (to the local operators) that it might require restart if the app crash.
