### ISSUE TITLE
Reinitialize the counter for the autointerval after one key has been changed

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_cityscopeJS_Projection#8]
Right now the interval is not reintialized so some time you can press to next and it will then very quickly change to the next slide

**Comment by agrignard** [comment]
What about setting a variable as soon as there is a human interaction to "stop " the loop?

**Comment by RELNO** [comment]
This can be done, but not in the `kiosk` mode. If you're ok with the tool be started every day/crash by local operators, than we can set the state to manual with clock => after Xmin go to auto mode => on click stop auto.

**Comment by RELNO** [comment]
Closing, not relevant at this point.
